# Generated by Django 6.0 on 2025-12-27 16:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_customuser_email_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата оплаты"
            ),
        ),
    ]
